- hosts: localhost
  gather_facts: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Mettre à jour le système
      apt:
        update_cache: yes
      become: yes

    - name: Installer Apache
      apt:
        name: apache2
        state: present
      become: yes

