---
- name: Envoyer des notifications de AWX à Discord
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Envoyer une notification à Discord
      uri:
        url: "https://discord.com/api/webhooks/1208946311643013210/wZ5PHFOgt4sRmer5w3Hyr8dd15GizUS-Y-Xa_JPAtztNv10Uo6Sc5AcgFHU2FAHysX7n"  # Remplacez WEBHOOK_ID et TOKEN par les valeurs de votre webhook Discord
        method: POST
        body_format: json
        headers:
          Content-Type: "application/json"
        body:
          content: "Test de notification depuis AWX vers Discord"
      register: discord_response
      
    - name: Afficher la réponse du serveur Discord
      debug:
        var: discord_response
