---
- name: Mise à jour des systèmes d'exploitation Debian et notification à Discord
  hosts: all
  become: true
  tasks:
    - name: Mise à jour des paquets Debian
      apt:
        upgrade: yes
        update_cache: yes
      register: apt_update_result

    - name: Envoyer une notification à Discord en cas de succès de la mise à jour
      when: apt_update_result.changed
      uri:
        url: "https://discord.com/api/webhooks/,,,"  # Remplacez WEBHOOK_ID et TOKEN par les valeurs de votre webhook Discord
        method: POST
        body_format: json
        headers:
          Content-Type: "application/json"
        body:
          content: "La mise à jour des paquets Debian a été effectuée avec succès sur {{ ansible_hostname }}"
      register: discord_response_success

    - name: Envoyer une notification à Discord en cas d'échec de la mise à jour
      when: apt_update_result.failed
      uri:
        url: "https://discord.com/api/webhooks/,,,,n"  # Remplacez WEBHOOK_ID et TOKEN par les valeurs de votre webhook Discord
        method: POST
        body_format: json
        headers:
          Content-Type: "application/json"
        body:
          content: "Échec lors de la mise à jour des paquets Debian sur {{ ansible_hostname }}"
      register: discord_response_failure

    - name: Afficher la réponse du serveur Discord en cas de succès
      debug:
        var: discord_response_success

    - name: Afficher la réponse du serveur Discord en cas d'échec
      debug:
        var: discord_response_failure



